<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN-BLR-L0117" name="Personal loan" tests="2" failures="1" timestamp="10 Sep 2021 15:26:22 GMT" time="0.026" errors="0">
  <testcase name="Demo" time="0.009" classname="Test.Day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Test.Day1.Demo(Day1.java:18)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="day2" time="0.002" classname="Test.Day2"/>
</testsuite> <!-- Personal loan -->
